<!-- qr_code_generator.blade.php -->

@extends('backend.layouts.app') <!-- If you have a master layout, extend it -->

@section('content')
    <div>
        <!-- Display any previous QR codes generated by the user -->


        <!-- QR code generator form -->
        <form action="{{ route('generate_qr_code.post') }}" method="POST">
            @csrf
            <!-- Add any necessary form inputs here -->

            <!-- Example: If you want the user to input a name -->
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" required>

            <button type="submit">Generate QR Code</button>
        </form>
        <div class="div">

        </div>
    </div>
@endsection
